const MEMBER_MESSAGES = {
  lang: "ENGLISH",
  pending: "pending",
  rejected: "rejected",
  accepted: "accepted",
  premium: "Premium",
  approvalPending: "Your account is pending administrator approval.",
  approvalReject: "Your account has been rejected by the administrator.",
  incorrect_password: "INCORRECT_PASSWORD",
  email_not_found: "EMAIL_NOT_REGISTERED",
  emailNotRegis: "This email not registered with us.",
  emailReq: "Please enter email address.",
  otp_not_verified: "OTP_NOT_VERIFIED",
  emailAlreadyExist: "THIS_DATA_ALREADY_EXIST",
  otpSent: "A one-time password (OTP) has been sent to your email address.",
  invalidOtp: "Invalid OTP, please try again.",
  otpVerified: "Otp verified successfully.",
  memberReq: "MEMBER_ID_REQUIRED",
  idSelfieReq: "MISSING_ID_AND_SELFIE",
  resetLink: "Reset Password Link is sent on your email.",
  resetTokenReq: "MISSING_RESET_TOKEN.",
  resetTokenExp: "The reset token has expired.",
  tokenWorking: "Token is Working.",
  invalidResetToken: "Invalid reset token or password.",
  passChangeSuccessully: "Password changed successfully.",
  passReq: "Please enter new password.",
  mNotFound: "Member not found.",
  adminApprovalReq: "Your account requires administrator approval.",
  profileCreated: "Profile created successfully.",
  profileAlreadyCreated: "Profile has already been created.",
  requestCompleted: "Request completed successfully.",
  quoteAlreadyCreated: "QUOTE_ALREADY_CREATED",
  quoteLimitReached: "This member has reached their monthly quote limit.",
  quoteCreated: "Quote successfully created.",
  categoriesFetched: "All categories fetched successfully.",
  categoryReq: "Please provide category.",
  profileNotFound: "PROFILE_NOT_FOUND",
  premiumRequiredForSocialLinks:
    "Only premium members can update social links.",
  noChangesDetected: "No changes detected",
  profileUpdatePendingApproval: "Profile update submitted for admin approval.",
  skillReq: "please provide skill.",
  invalidAdminApprovalType: "INVALID_ADMIN_APPROVAL_TYPE",
  invalidMembershipType: "INVALID_MEMBERSHIP_TYPE",
  createdSuccessfully: "Created successfully.",
  dataNotExist: "DATA_NOT_EXIST",
  oldPasswordIncorrect: "Old password is incorrect.",
  invalidSocialLinksFormat: "The provided social links format is invalid.",

  registration_success:
    "Your account is successfully created. Please check your email and verify your OTP.",

  login_success: "Login successfully.",
  password_invalid: "Please enter a valid password.",

  admin_approval_required: "Administrator approval required.",
  only_premium_social_link: "Only premium members can update social links.",
  invalid_photo_gallery: "Photo gallery must be an array.",
  file_uploaded: "Member files uploaded successfully.",

  planNotFound: "Plan not found",
  notAllowLink: "Your plan does not allow adding social links",
  notAllowPhoto: "Your plan does not allow uploading photo gallery",
  subscriptionReq: "Active subscription required to create a profile",
  // jobNotFound:""
};

export default MEMBER_MESSAGES;
